[package]
authors = ["HansiHE <hansihe@hansihe.com>"]
name = "beam_compile"
version = "0.1.0"

[dependencies]
beam_file = "0.2.2"
byteorder = "1.1.0"
eetf = "0.3.6"
itertools = "0.6.0"
regex = "0.2.2"
